name: publish
on: [release]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: publish
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
        working-directory: ./tellodji
      - run: python -m pip install poetry
      - run: poetry publish --build --username __token__ --password $PYPI_TOKEN
