name: Build and Publish to PyPi
on:
  release:
    types: [published]
  workflow_dispatch:
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Build and Publish to PyPi
        run: python -m pip install poetry
      - run: poetry self update --preview
      - run: poetry publish --build -f wheel -u __token__ -p $PYPI_TOKEN
