name: publish
on:
  release:
  workflow_dispatch:
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Build and Publish to PyPi
        run: python -m pip install poetry
      - run: poetry publish --build --username __token__ --password $PYPI_TOKEN
